name: proyecto_av
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  quickalert: ^1.1.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  table_calendar: ^3.1.2
  carousel_slider: ^5.0.0
  crypto: ^3.0.3
  # --- ¡AGREGA ESTAS DOS LÍNEAS! ---
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0

  

  # AÑADIDO: Para las notificaciones locales
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  rxdart: ^0.28.0 # Dependencia requerida por flutter_local_notifications

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/login_bg.png
    - assets/images/home_bg.png

# --- ¡AÑADE ESTO AL FINAL DE TODO EL ARCHIVO! ---
flutter_launcher_icons:
  android: true  # Le decimos que SÍ genere para Android
  ios: true      # Le decimos que SÍ genere para iOS
  image_path: "assets/images/logo.png" # ¡LA RUTA EXACTA A TU IMAGEN!
# ------------------------------------------------